name: Run tests

on:
  push:
  pull_request:

jobs:
  run-tox:
    name: test-${{ matrix.python-version }}
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13.0-rc.1 - 3.13"
          - "pypy-3.8"
          - "pypy-3.9"
          - "pypy-3.10"

      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade tox

      - name: Run tests
        run: |
          tox -e py

  run-lint:
    name: lint
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.12"

      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade tox

      - name: Run lint
        run: |
          tox -e flake8
